# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GaussianBlur": "01-augmentations.ipynb",
         "RandomGaussianBlur": "01-augmentations.ipynb",
         "get_kornia_batch_augs": "01-augmentations.ipynb",
         "get_torchvision_batch_augs": "01-augmentations.ipynb",
         "get_fastai_batch_augs": "01-augmentations.ipynb",
         "get_batch_augs": "01-augmentations.ipynb",
         "create_fastai_encoder": "02-layers.ipynb",
         "create_timm_encoder": "02-layers.ipynb",
         "create_encoder": "02-layers.ipynb",
         "create_mlp_module": "02-layers.ipynb",
         "create_cls_module": "02-layers.ipynb",
         "create_model": "02-layers.ipynb",
         "SimCLRModel": "10-simclr.ipynb",
         "create_simclr_model": "10-simclr.ipynb",
         "remove_diag": "10-simclr.ipynb",
         "SimCLRLoss": "10-simclr.ipynb",
         "SimCLR": "10-simclr.ipynb",
         "create_simclrV2_model": "10b-simclr_v2.ipynb",
         "SimCLRV2Loss": "10b-simclr_v2.ipynb",
         "SimCLRV2": "10b-simclr_v2.ipynb",
         "BYOLModel": "20-byol.ipynb",
         "create_byol_model": "20-byol.ipynb",
         "symmetric_mse_loss": "20-byol.ipynb",
         "byol_loss": "20-byol.ipynb",
         "BYOL": "20-byol.ipynb",
         "SwAVModel": "30-swav.ipynb",
         "create_swav_model": "30-swav.ipynb",
         "sinkhorn_knopp": "30-swav.ipynb",
         "SWAVLoss": "30-swav.ipynb",
         "SWAV": "30-swav.ipynb",
         "MoCoModel": "40-moco.ipynb",
         "create_moco_model": "40-moco.ipynb",
         "MOCO": "40-moco.ipynb"}

modules = ["augmentations.py",
           "layers.py",
           "simclr.py",
           "simclr_v2.py",
           "byol.py",
           "swav.py",
           "moco.py"]

doc_url = "https://keremturgutlu.github.io/self_supervised/"

git_url = "https://github.com/keremturgutlu/self_supervised/tree/master/"

def custom_doc_links(name): return None
