# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_aug_pipe": "10-byol.ipynb",
         "create_encoder": "10-byol.ipynb",
         "MLP": "10-byol.ipynb",
         "BYOLModel": "10-byol.ipynb",
         "create_byol_model": "10-byol.ipynb",
         "cosine_similarity": "10-byol.ipynb",
         "symmetric_mse_loss": "10-byol.ipynb",
         "byol_loss": "10-byol.ipynb",
         "BYOL": "10-byol.ipynb"}

modules = ["byol.py"]

doc_url = "https://keremturgutlu.github.io/self_supervised/"

git_url = "https://github.com/keremturgutlu/self_supervised/tree/master/"

def custom_doc_links(name): return None
