# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00-utils.ipynb (unless otherwise specified).

__all__ = ['transfer_learn']

# Cell
from fastai.vision.all import *

# Cell
def transfer_learn(learn:Learner, weights_path:Path, device:torch.device=None):
    "Load and freeze pretrained weights inplace from `weights_path` using `device`"
    if device is None: device = learn.dls.device
    new_state_dict = torch.load(weights_path, map_location=device)
    if 'model' in new_state_dict.keys(): new_state_dict = new_state_dict['model']
    #allow for simply exporting the raw PyTorch model
    learn_state_dict = learn.model.state_dict()
    for name, param in learn_state_dict.items():
        name = 'encoder.'+name[2:]
        if name in new_state_dict:
            input_param = new_state_dict[name]
            if input_param.shape == param.shape:
                param.copy_(input_param)
            else:
                print('Shape mismatch at:', name, 'skipping')
        else: pass # these are weights that weren't in the original model, such as a new head
    learn.model.load_state_dict(learn_state_dict)
    learn.freeze()
    print("Weights successfully transferred!")